apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: inventory-api
  description: API for inventory-service
  links:
   - url: http://localhost:8080/swagger-ui.html
     title: Swagger UI
  tags:
    - http
spec:
  type: thrift
  lifecycle: production
  owner: group:guests
  system: inventory-app
  definition: |
    openapi: 3.0.1
    info:
      title: OpenAPI definition
      version: v0
    servers:
      - url: http://localhost:8080
        description: Generated server url
    paths:
      /api/v1/inventorys/{id}/name:
        put:
          tags:
            - inventory-api
          operationId: updateName
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          requestBody:
            content:
              application/json:
                schema:
                  type: string
            required: true
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
      /api/v1/inventorys/{id}/count:
        put:
          tags:
            - inventory-api
          operationId: updateCount
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          requestBody:
            content:
              application/json:
                schema:
                  type: integer
                  format: int32
            required: true
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
      /api/v1/inventorys:
        get:
          tags:
            - inventory-api
          operationId: list
          parameters:
            - name: name
              in: query
              required: false
              schema:
                type: string
            - name: count
              in: query
              required: false
              schema:
                type: integer
                format: int32
            - name: pageable
              in: query
              required: true
              schema:
                $ref: '#/components/schemas/Pageable'
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/inventory'
        post:
          tags:
            - inventory-api
          operationId: create
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/inventoryRequest'
            required: true
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
      /api/v1/inventorys/{id}/increment:
        post:
          tags:
            - inventory-api
          operationId: increment
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
      /api/v1/inventorys/{id}/decrement:
        post:
          tags:
            - inventory-api
          operationId: decrement
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
      /api/v1/inventorys/{id}:
        get:
          tags:
            - inventory-api
          operationId: get
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/inventory'
    components:
      schemas:
        inventory:
          required:
            - count
            - id
            - name
          type: object
          properties:
            name:
              type: string
            count:
              type: integer
              format: int32
            id:
              type: string
        inventoryRequest:
          required:
            - count
            - name
          type: object
          properties:
            name:
              type: string
            count:
              type: integer
              format: int32
        Pageable:
          type: object
          properties:
            page:
              minimum: 0
              type: integer
              format: int32
            size:
              minimum: 1
              type: integer
              format: int32
            sort:
              type: array
              items:
                type: string
